// src/utils/nihongStoreExport.ts
import { NihongStoreOrder } from "../types";
import { formatIDR, formatDate } from "./format";

/**
 * Menghasilkan format ringkasan teks daftar belanjaan untuk tim jastiper / admin di Jepang.
 * Siap disalin langsung ke grup WhatsApp / Telegram.
 */
export function generateShoppingListText(orders: NihongStoreOrder[]): string {
  if (orders.length === 0) return "";

  const timestamp = new Date().toLocaleDateString("id-ID", {
    weekday: "long",
    day: "numeric",
    month: "short",
    year: "numeric",
  });

  const lines: string[] = [];
  lines.push(`🇯🇵 *REKAP DAFTAR BELANJA JASTIP JEPANG*`);
  lines.push(`📅 Tanggal Rekap: ${timestamp}`);
  lines.push(`📦 Total Pesanan: ${orders.length} pesanan\n`);

  let totalItemsCount = 0;
  let totalAvailableItemsCount = 0;

  orders.forEach((order, ordIdx) => {
    const availableItems = order.items.filter((it) => it.status !== "Stok habis");
    const oosItems = order.items.filter((it) => it.status === "Stok habis");

    totalItemsCount += order.items.reduce((s, it) => s + (it.jumlah || 1), 0);
    totalAvailableItemsCount += availableItems.reduce((s, it) => s + (it.jumlah || 1), 0);

    lines.push(`━━━━━━━━━━━━━━━━━━━━━`);
    lines.push(`*#${ordIdx + 1}. PESANAN: ${order.no || order.id}*`);
    lines.push(`👤 Pemesan: *${order.namaPelanggan}* ${order.noTelponPelanggan ? `(${order.noTelponPelanggan})` : ""}`);
    if (order.assignedScheduleRoute) {
      lines.push(`✈️ Jadwal: ${order.assignedScheduleRoute} ${order.assignedScheduleDate ? `(${order.assignedScheduleDate})` : ""}`);
    }
    if (order.catatan) {
      lines.push(`📝 Catatan Order: _${order.catatan}_`);
    }

    lines.push(`\n🛍️ *Daftar Barang Belanja:*`);

    if (availableItems.length === 0) {
      lines.push(`  ⚠️ _(Semua item ditandai Stok Habis)_`);
    } else {
      availableItems.forEach((it, itIdx) => {
        const qty = it.jumlah || 1;
        const variants: string[] = [];
        if (it.kodeBarang) variants.push(`Kode: ${it.kodeBarang}`);
        if (it.warna) variants.push(`Warna: ${it.warna}`);
        if (it.ukuran) variants.push(`Size: ${it.ukuran}`);

        const variantStr = variants.length > 0 ? ` [${variants.join(" | ")}]` : "";
        lines.push(`  ${itIdx + 1}. *${it.namaBarang}* x *${qty} pcs*${variantStr}`);
        
        if (it.catatan) {
          lines.push(`     ↳ 💬 Catatan: _${it.catatan}_`);
        }
        if (it.url) {
          lines.push(`     ↳ 🔗 Link: ${it.url}`);
        }
      });
    }

    if (oosItems.length > 0) {
      lines.push(`\n❌ *Barang Stok Habis / Skip:*`);
      oosItems.forEach((it) => {
        lines.push(`  • ~${it.namaBarang}~ (x${it.jumlah || 1}) ${it.catatan ? `— _${it.catatan}_` : ""}`);
      });
    }

    lines.push("");
  });

  lines.push(`━━━━━━━━━━━━━━━━━━━━━`);
  lines.push(`📊 *TOTAL ITEM AKTIF DIBELANJAKAN: ${totalAvailableItemsCount} pcs*`);
  lines.push(`_Generated by NihongTeam ERP_`);

  return lines.join("\n");
}
